Output demo.gif

Set Width 1650
Set Height 600


# Step 1: List files
Type "ls -1"
Enter
Sleep 2

Hide
Type "clear"
Enter
Show

# Step 2: Generate Go bindings
Type "go generate"
Enter
Sleep 2

Hide
Type "clear"
Enter
Show

# Step 1: List files
Type "ls -1"
Enter
Sleep 2

Hide
Type "clear"
Enter
Show

# Step 3: Run the Go program
Type "sudo go run ."
Enter
Sleep 15

# Step 4: Stop the program
Ctrl+C
Sleep 2

Type "✅ eBPF XDP packet drop demo complete 🎉"
Sleep 2
